export const STATES_LIST = [
  'AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 
  'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 
  'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 
  'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 
  'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY'
];

export const MAJORS_LIST = [
  'Accounting',
  'Art & Design',
  'Biology',
  'Biomedical Engineering',
  'Business Administration',
  'Chemical Engineering',
  'Chemistry',
  'Civil Engineering',
  'Communications',
  'Computer Engineering',
  'Computer Science',
  'Cybersecurity',
  'Data Science',
  'Economics',
  'Electrical Engineering',
  'Finance',
  'Information Technology',
  'Marketing',
  'Mathematics',
  'Mechanical Engineering',
  'Nursing',
  'Physics',
  'Political Science',
  'Psychology',
  'Pre-Law',
  'Pre-Med',
  'Software Engineering'
];

export const UNIVERSITIES_LIST = [
  'Boston University',
  'Columbia University',
  'Cornell University',
  'Georgia Institute of Technology',
  'Harvard University',
  'Massachusetts Institute of Technology (MIT)',
  'New York University (NYU)',
  'Ohio State University',
  'Penn State University',
  'Princeton University',
  'Purdue University',
  'Rutgers University',
  'Stanford University',
  'University of California, Berkeley',
  'University of California, Los Angeles (UCLA)',
  'University of Florida',
  'University of Illinois Urbana-Champaign',
  'University of Maryland',
  'University of Michigan',
  'University of Southern California (USC)',
  'University of Texas at Austin',
  'University of Washington',
  'Yale University'
];

export const INDUSTRIES_LIST = [
  'Aerospace',
  'Agriculture',
  'Automotive',
  'Biotechnology',
  'Construction',
  'Consulting',
  'Education',
  'Energy',
  'Entertainment',
  'Finance',
  'Government',
  'Healthcare',
  'Hospitality',
  'Information Technology',
  'Insurance',
  'Legal',
  'Manufacturing',
  'Media',
  'Non-profit',
  'Real Estate',
  'Retail',
  'Software Engineering / Technology',
  'Telecommunications',
  'Transportation'
];
